#
# Cookbook Name:: shelly
# Provider:: alias
#
# Copyright (c) 2015 Tnarik Innael, All Rights Reserved.

use_inline_resources if defined?(use_inline_resources)

def whyrun_supported?
  true
end

require 'etc'
action :add do
  file = Chef::Resource::File.new(destination, run_context)
  file.owner(new_resource.owner)
  file.group(new_resource.group || Etc.getpwnam(new_resource.user).gid)
  file.mode(new_resource.mode)
  file.content(<<-EOH.gsub(/^ {8}/, ''))
    #
    # This file was generated by Chef for #{node['fqdn']}
    # Do NOT modify this file by hand!
    #
    alias #{new_resource.alias_name}="#{new_resource.command}"
  EOH
  file.run_action(:create)
end

action :remove do
  file = Chef::Resource::File.new(destination, run_context)
  file.run_action(:delete)
end

def destination
  "#{new_resource.destination || node[:shelly][:destination]}/#{filename}.sh"
end

def filename
  new_resource.alias_name.to_s.gsub(/\s/, '_')
end